// ==========================
// GENERATE PERSONA
// ==========================
function generatePersona() {
  const nama = document.getElementById("nama").value;
  const hobi = document.getElementById("hobi").value.toLowerCase();
  const angka = parseInt(document.getElementById("angka").value);

  let persona = "";
  const sound = document.getElementById("bgSound");

  // 🔥 KHUSUS ABEL
  if (nama.toLowerCase() === "abel") {
    persona = "✨ The Monkey King\nSun Wu Bel";

    // 🔊 SOUND
    sound.currentTime = 0;
    sound.play();

    // 🌌 EFFECT
    document.body.style.boxShadow = "0 0 60px purple inset";
  } 
  else {
    // STOP SOUND
    sound.pause();
    sound.currentTime = 0;

    // LOGIC UMUM
    if (hobi.includes("game") || hobi.includes("coding")) {
      persona = angka > 5 
        ? "🧠 The Genius Strategist\nMaster of tactics."
        : "🎮 The Silent Hacker\nWorks in the shadows.";
    } 
    else if (hobi.includes("musik") || hobi.includes("art")) {
      persona = angka > 5 
        ? "🎨 The Dreamy Artist\nCreates imagination."
        : "🌙 The Moon Dreamer\nLives in dreams.";
    } 
    else if (hobi.includes("olahraga")) {
      persona = angka > 5 
        ? "🔥 The Flame Warrior\nFull of passion."
        : "⚔️ The Lone Samurai\nCalm and deadly.";
    } 
    else {
      persona = angka > 5 
        ? "🐉 The Dragon Tamer\nControls power."
        : "🌸 The Silent Wanderer\nWalks quietly.";
    }

    // BONUS NAMA
    if (nama.toLowerCase().startsWith("a")) {
      persona += "\n✨ The Chosen One";
    }

    // RESET EFFECT
    document.body.style.boxShadow = "none";
  }

  // OUTPUT KE UI
  document.getElementById("result").innerText = persona;
  document.getElementById("profileName").innerText = nama || "M . Abel Cakrawangsa";
}


// ==========================
// DOWNLOAD PDF
// ==========================
async function downloadPDF() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const nama = document.getElementById("nama").value || "Unknown";
  const persona = document.getElementById("result").innerText;

  // =========================
  // BACKGROUND HEADER
  // =========================
  doc.setFillColor(30, 41, 59); // dark blue
  doc.rect(0, 0, 210, 40, "F");

  // =========================
  // TITLE
  // =========================
  doc.setTextColor(255, 255, 255);
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Bel PERSONA RESULT", 20, 25);

  // =========================
  // RESET TEXT COLOR
  // =========================
  doc.setTextColor(0, 0, 0);

  // =========================
  // NAMA
  // =========================
  doc.setFontSize(12);
  doc.setFont("Helvetica", "bold");
  doc.text("Nama:", 20, 60);

  doc.setFont("Helvetica", "normal");
  doc.text(nama, 50, 60);

  // =========================
  // GARIS PEMBATAS
  // =========================
  doc.setDrawColor(100);
  doc.line(20, 65, 190, 65);

  // =========================
  // BOX PERSONA
  // =========================
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(20, 75, 170, 80, 5, 5, "F");

  // =========================
  // TEXT PERSONA
  // =========================
  doc.setFontSize(12);
  doc.setFont("Helvetica", "bold");
  doc.text("Your Persona:", 25, 90);

  doc.setFont("Helvetica", "normal");

  const splitText = doc.splitTextToSize(persona, 150);
  doc.text(splitText, 25, 100);

  // =========================
  // FOOTER
  // =========================
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Generated by Persona Bel", 20, 180);

  // =========================
  // SAVE
  // =========================
  doc.save("persona.pdf");
}